"""
Bharat Sign AI 3 - Global Sign Languages Registry (60+ Universal Dialects)
"""

GLOBAL_SIGN_LANGUAGES = [
    {"code": "ISL", "name": "ISL (Indian Sign Language)"},
    {"code": "ASL", "name": "ASL (American Sign Language)"},
    {"code": "BSL", "name": "BSL (British Sign Language)"},
    {"code": "Auslan", "name": "Auslan (Australian Sign Language)"},
    {"code": "LSF", "name": "LSF (French Sign Language / Langue des Signes Française)"},
    {"code": "DGS", "name": "DGS (German Sign Language / Deutsche Gebärdensprache)"},
    {"code": "JSL", "name": "JSL (Japanese Sign Language / Nihon Shuwa)"},
    {"code": "KSL", "name": "KSL (Korean Sign Language / Hanguk Suwa)"},
    {"code": "CSL", "name": "CSL (Chinese Sign Language / Zhongguo Shouyu)"},
    {"code": "INT", "name": "INT (International Sign / Gestuno)"},
    {"code": "Libras", "name": "Libras (Brazilian Sign Language)"},
    {"code": "LSFB", "name": "LSFB (Belgian French Sign Language)"},
    {"code": "LSM", "name": "LSM (Mexican Sign Language)"},
    {"code": "LSE", "name": "LSE (Spanish Sign Language / Lengua de Signos Española)"},
    {"code": "LIS", "name": "LIS (Italian Sign Language / Lingua dei Segni Italiana)"},
    {"code": "NGT", "name": "NGT (Dutch Sign Language / Nederlandse Gebarentaal)"},
    {"code": "PJM", "name": "PJM (Polish Sign Language / Polski Język Migowy)"},
    {"code": "RSL", "name": "RSL (Russian Sign Language / Русский жестовый язык)"},
    {"code": "SASL", "name": "SASL (South African Sign Language)"},
    {"code": "ISL_IL", "name": "ISL (Israeli Sign Language)"},
    {"code": "TSL", "name": "TSL (Taiwanese Sign Language)"},
    {"code": "FSL", "name": "FSL (Filipino Sign Language)"},
    {"code": "NZSL", "name": "NZSL (New Zealand Sign Language)"},
    {"code": "HKSL", "name": "HKSL (Hong Kong Sign Language)"},
    {"code": "VGT", "name": "VGT (Flemish Sign Language)"},
    {"code": "MSL", "name": "MSL (Malaysian Sign Language)"},
    {"code": "ÖGS", "name": "ÖGS (Austrian Sign Language)"},
    {"code": "ČSJ", "name": "ČSJ (Czech Sign Language)"},
    {"code": "DSL", "name": "DSL (Danish Sign Language)"},
    {"code": "ETH", "name": "ETH (Ethiopian Sign Language)"},
    {"code": "FSD", "name": "FSD (Finnish Sign Language)"},
    {"code": "GSL", "name": "GSL (Greek Sign Language)"},
    {"code": "MHJ", "name": "MHJ (Hungarian Sign Language)"},
    {"code": "İSL", "name": "İSL (Icelandic Sign Language)"},
    {"code": "ISL_IR", "name": "ISL (Irish Sign Language)"},
    {"code": "LIU", "name": "LIU (Jordanian Sign Language)"},
    {"code": "KSL_KE", "name": "KSL (Kenyan Sign Language)"},
    {"code": "LGK", "name": "LGK (Lithuanian Sign Language)"},
    {"code": "MSL_MY", "name": "MSL (Myanmar Sign Language)"},
    {"code": "NSL", "name": "NSL (Norwegian Sign Language)"},
    {"code": "LGP", "name": "LGP (Portuguese Sign Language)"},
    {"code": "LSR", "name": "LSR (Romanian Sign Language)"},
    {"code": "SSL", "name": "SSL (Swedish Sign Language)"},
    {"code": "TSL_TH", "name": "TSL (Thai Sign Language)"},
    {"code": "TİD", "name": "TİD (Turkish Sign Language)"},
    {"code": "USL", "name": "USL (Ukrainian Sign Language)"},
    {"code": "VSL", "name": "VSL (Vietnamese Sign Language)"},
    {"code": "ASL_AR", "name": "Argentine Sign Language"},
    {"code": "ASL_CL", "name": "Chilean Sign Language"},
    {"code": "ASL_CO", "name": "Colombian Sign Language"},
    {"code": "ASL_PE", "name": "Peruvian Sign Language"},
    {"code": "ASL_VE", "name": "Venezuelan Sign Language"},
    {"code": "ISL_IN", "name": "Indonesian Sign Language (BISINDO)"},
    {"code": "NSL_NE", "name": "Nepalese Sign Language"},
    {"code": "SSL_SL", "name": "Sri Lankan Sign Language"},
    {"code": "BD_SL", "name": "Bengali Sign Language (BD-SL)"},
    {"code": "PK_SL", "name": "Pakistani Sign Language (PSL)"},
    {"code": "EGY_SL", "name": "Egyptian Sign Language"},
    {"code": "SA_SL", "name": "Saudi Sign Language"},
    {"code": "AE_SL", "name": "UAE Sign Language"},
]
